package org.eclipse.acceleo.module.umlToJpa.main;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.eclipse.acceleo.common.utils.ModelUtils;
import org.eclipse.acceleo.module.umlToJpa.exception.DiagramaInvalidoException;
import org.eclipse.acceleo.module.umlToJpa.util.GerenciadorDeElementosDoModelo;
import org.eclipse.emf.common.util.BasicMonitor;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.uml2.uml.UMLPackage;
import org.eclipse.uml2.uml.resource.UMLResource;

public class Formulario extends javax.swing.JFrame {

	/**
	 * Creates new form FormularioTeste
	 */
	public Formulario() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		heranca = new javax.swing.ButtonGroup();
		colecoes = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		modelo = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		botaoGerar = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		destino = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		single = new javax.swing.JRadioButton();
		join = new javax.swing.JRadioButton();
		perClass = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		lista = new javax.swing.JRadioButton();
		set = new javax.swing.JRadioButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("GenJPA: UML to Java / JPA");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText("GENJPA: UML TO JAVA/JPA");

		modelo.setEditable(false);
		modelo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				modeloActionPerformed(evt);
			}
		});

		jButton1.setText("Selecionar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		botaoGerar.setText("Gerar");
		botaoGerar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoGerarActionPerformed(evt);
			}
		});

		jLabel2.setText("Selecione o arquivo .uml:");

		destino.setEditable(false);

		jButton3.setText("Selecionar");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel3.setText("Pasta de Destino: ");

		heranca.add(single);
		single.setSelected(true);
		single.setText("Single Table");
		single.setActionCommand("SINGLE_TABLE");

		single.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				singleActionPerformed(evt);
			}
		});

		heranca.add(join);
		join.setText("Join Table");
		join.setActionCommand("JOINED");

		heranca.add(perClass);
		perClass.setText("Table Per Class");
		perClass.setActionCommand("TABLE_PER_CLASS");

		jLabel4.setText("Tipo de Herança: ");

		jLabel5.setText("Tipo de Coleções:");

		colecoes.add(lista);
		lista.setSelected(true);
		lista.setText("List");
		lista.setActionCommand("List");

		colecoes.add(set);
		set.setText("Set");
		set.setActionCommand("Set");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(147,
																										147,
																										147)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														join)
																												.addComponent(
																														botaoGerar,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														77,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														set)))
																				.addComponent(
																						single))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		49,
																		Short.MAX_VALUE)
																.addComponent(
																		perClass)
																.addGap(15, 15,
																		15))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										modelo,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										298,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButton1,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										89,
																										Short.MAX_VALUE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addGap(0,
																										0,
																										Short.MAX_VALUE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										destino,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										297,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButton3,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)))
																.addGap(10, 10,
																		10))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						lista))
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														modelo,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1))
								.addGap(18, 18, 18)
								.addComponent(jLabel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														destino,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton3))
								.addGap(13, 13, 13)
								.addComponent(jLabel4)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(single)
												.addComponent(join)
												.addComponent(perClass))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel5)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lista)
												.addComponent(set))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										16, Short.MAX_VALUE)
								.addComponent(botaoGerar).addContainerGap()));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser cs = new JFileChooser();
		cs.setFileSelectionMode(JFileChooser.FILES_ONLY);
		cs.setAcceptAllFileFilterUsed(false);
		cs.addChoosableFileFilter(new FileNameExtensionFilter("UML files",
				"uml"));
		int retorno = cs.showOpenDialog(null);
		if (retorno == JFileChooser.APPROVE_OPTION) {
			arquivoUML = cs.getSelectedFile();
			modelo.setText(arquivoUML.getAbsolutePath());
		}
	}

	private void modeloActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser cs = new JFileChooser();
		cs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		cs.setAcceptAllFileFilterUsed(false);
		int retorno = cs.showOpenDialog(null);
		if (retorno == JFileChooser.APPROVE_OPTION) {
			pastaDestino = cs.getSelectedFile();
			destino.setText(pastaDestino.getAbsolutePath());
		}
	}

	private void botaoGerarActionPerformed(java.awt.event.ActionEvent evt) {
		if(arquivoUML!=null && pastaDestino!=null){
			ResourceSetImpl resourceSet = new ResourceSetImpl();
			resourceSet.getPackageRegistry().put(org.eclipse.uml2.uml.UMLPackage.eINSTANCE.getNsURI(), org.eclipse.uml2.uml.UMLPackage.eINSTANCE);
			resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put(UMLResource.FILE_EXTENSION, UMLResource.Factory.INSTANCE);
			resourceSet.getPackageRegistry().put(UMLPackage.eNS_URI, UMLPackage.eINSTANCE);
			resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put(UMLResource.FILE_EXTENSION, UMLResource.Factory.INSTANCE);
			Map uriMap = resourceSet.getURIConverter().getURIMap();
			
			URI uri = URI.createURI("jar:file:/C:/Users/Rhaylson/OneDrive/workspace/org.eclipse.acceleo.module.umlToJpa/libs/uml.jar!/");
			uriMap.put(URI.createURI(UMLResource.LIBRARIES_PATHMAP), uri.appendSegment("libraries").appendSegment(""));
			uriMap.put(URI.createURI(UMLResource.METAMODELS_PATHMAP), uri.appendSegment("metamodels").appendSegment(""));
			uriMap.put(URI.createURI(UMLResource.PROFILES_PATHMAP), uri.appendSegment("profiles").appendSegment(""));
			try {
				EObject modelo = ModelUtils.load(arquivoUML, resourceSet);
				Main geradorDeCodigo = new Main(modelo, new File("C:/Users/Rhaylson/OneDrive/workspace/org.eclipse.acceleo.module.umlToJpa/generate"), new ArrayList<String>());
				geradorDeCodigo.doGenerate(new BasicMonitor());
				GerenciadorDeElementosDoModelo gm = new GerenciadorDeElementosDoModelo(getTipoLista(),getTipoHeranca(),pastaDestino.getAbsolutePath());
				gm.gerarCodigo();
				JOptionPane.showMessageDialog(null, "Transformação finalizada. As classes foram criadas na pasta de destino.","Confirmação", JOptionPane.INFORMATION_MESSAGE);
			} catch (IOException e) {
			}catch (DiagramaInvalidoException e2){
				JOptionPane.showMessageDialog(null, e2.getMessage(),"Problemas no diagrama", JOptionPane.ERROR_MESSAGE);
			}
			
			setVisible(false);
		}
	}

	private void singleActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	
	public void executar(){
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Formulario.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Formulario.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Formulario.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Formulario.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Formulario().setVisible(true);
			}
		});
	}
	
	public File getArquivoUML(){
		return arquivoUML;
	}
	
	public File getPastaDestino(){
		return pastaDestino;
	}
	
	public String getTipoLista(){
		return colecoes.getSelection().getActionCommand();
	}
	
	public String getTipoHeranca(){
		return heranca.getSelection().getActionCommand();
	}

	private javax.swing.JButton botaoGerar;
	private javax.swing.ButtonGroup colecoes;
	private javax.swing.JTextField destino;
	private javax.swing.ButtonGroup heranca;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JRadioButton join;
	private javax.swing.JRadioButton lista;
	private javax.swing.JTextField modelo;
	private javax.swing.JRadioButton perClass;
	private javax.swing.JRadioButton set;
	private javax.swing.JRadioButton single;
	private File arquivoUML;
	private File pastaDestino;
}
